In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

DATA_DIR = Path("../data")

main_path = DATA_DIR / "DataSheet_Main.csv"
country_meta_path = DATA_DIR / "Metadata_Country.csv"
indicator_meta_path = DATA_DIR / "Metadata_Indicators.csv"

gdp_path = DATA_DIR / "DataSheet_GDP.csv"
country_meta_gdp_path = DATA_DIR / "Metadata_Country_GDP.csv"
indicator_meta_gdp_path = DATA_DIR / "Metadata_Indicator_GDP.csv"

Matplotlib is building the font cache; this may take a moment.

In [ ]:
df = pd.read_csv(main_path, skiprows = 4)
country_meta = pd.read_csv(country_meta_path)
indicator_meta = pd.read_csv(indicator_meta_path)

df_gdp = pd.read_csv(gdp_path, skiprows = 4)
country_meta_gdp = pd.read_csv(country_meta_gdp_path)
indicator_meta_gdp = pd.read_csv(indicator_meta_gdp_path)

df = df.dropna(axis = 1, how="all")
country_meta = country_meta.dropna(axis = 1, how = "all")
indicator_meta = indicator_meta.dropna(axis = 1, how = "all")

df_gdp = df_gdp.dropna(axis = 1, how="all")
country_meta_gdp = country_meta_gdp.dropna(axis = 1, how = "all")
indicator_meta_gdp = indicator_meta_gdp.dropna(axis = 1, how = "all")

In [ ]:
print("Main dataset:")
display(df)
print(df.shape)
print(df.columns)

print("Main dataset:")
display(df_gdp)
print(df_gdp.shape)
print(df_gdp.columns)

Main dataset:

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,International migrant stock (% of population),SM.POP.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.476210e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aruba,ABW,"International migrant stock, total",SM.POP.TOTL,7893.0,NaN,NaN,NaN,NaN,7677.0,...,NaN,3.611400e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aruba,ABW,Net migration,SM.POP.NETM,0.0,-569.0,-609.0,-646.0,-684.0,-726.0,...,8.800000e+01,1.770000e+02,1.700000e+02,2.180000e+02,3.670000e+02,4.120000e+02,0.000000e+00,5.010000e+02,1.640000e+02,157.0
3,Aruba,ABW,Average transaction cost of sending remittance...,SI.RMT.COST.OB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aruba,ABW,Average transaction cost of sending remittance...,SI.RMT.COST.IB.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20211,Zimbabwe,ZWE,"Portfolio investment, net (BoP, current US$)",BN.KLT.PTXL.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.303000e+08,-1.228000e+08,8.006134e+07,1.008818e+08,-5.473016e+07,-3.718164e+06,8.164653e+07,NaN,NaN,NaN
20212,Zimbabwe,ZWE,"Foreign direct investment, net (BoP, current US$)",BN.KLT.DINV.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,-4.728000e+08,-3.992000e+08,-3.430138e+08,-3.062531e+08,-7.170786e+08,-2.470963e+08,-1.538600e+08,NaN,NaN,NaN
20213,Zimbabwe,ZWE,"Personal remittances, paid (current US$)",BM.TRF.PWKR.CD.DT,NaN,NaN,NaN,NaN,NaN,NaN,...,1.084092e+07,1.135044e+07,1.384487e+07,1.857500e+07,2.927889e+07,1.348057e+07,2.170709e+07,NaN,NaN,NaN
20214,Zimbabwe,ZWE,"Foreign direct investment, net outflows (% of ...",BM.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,3.693156e-01,1.102032e-01,1.557278e-01,5.315228e-03,2.303353e-03,1.101003e-02,-1.627173e-02,1.127903e-01,6.211946e-02,NaN
20215,Zimbabwe,ZWE,"Foreign direct investment, net outflows (BoP, ...",BM.KLT.DINV.CD.WD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.200000e+07,2.200000e+07,3.200000e+07,9.346770e+05,7.867350e+05,2.403735e+06,-3.500000e+06,3.200000e+07,1.700000e+07,NaN

(20216, 68)
Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023'],
      dtype='str')
Main dataset:

,Country Name,Country Code,Indicator Name,Indicator Code,1961,1962,1963,1964,1965,1966,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.611480,1.234335,3.493430,3.212471,1.225112,-23.897990,14.730616,10.636431,7.706798,6.810777
1,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.418937,7.937038,5.623764,4.649241,5.138168,4.827421,...,2.934030,2.130117,2.677524,2.705194,2.030077,-2.817572,4.578772,3.722717,1.931160,2.763839
2,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.451315,2.260314,2.647003,1.189228,3.911603,-2.351101,-20.738839,-6.240172,2.266944,NaN
3,Africa Western and Central,AFW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1.869593,3.726090,7.038388,5.364089,4.105339,-1.513011,...,2.932864,0.194316,2.296349,2.904664,3.281683,-3.730630,2.549691,4.472795,3.662428,4.585674
4,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.763178,-1.700530,-0.149396,-0.594411,-0.204680,-4.042447,2.102753,4.216003,1.263308,4.423907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.916231,5.571775,4.825656,3.406632,4.756801,-5.340275,10.745656,4.278499,4.067627,4.573097
262,"Yemen, Rep.",YEM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-27.994546,-9.375124,-5.071796,0.752448,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,3.844734,6.177931,7.373709,7.939609,6.122798,4.438386,...,1.321862,0.664552,1.157947,1.556784,0.259936,-6.168918,4.858649,2.058137,0.806105,0.534844
264,Zambia,ZMB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,...,2.920375,3.755100,3.525863,4.034494,1.441306,-2.785055,6.234922,5.211224,5.367943,3.820048
265,Zimbabwe,ZWE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,...,1.779854,0.755794,4.734411,5.009922,-6.332450,-7.816951,8.468017,6.139263,5.350869,1.742395

(266, 68)
Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969',
       '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978',
       '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023',
       '2024'],
      dtype='str')

In [ ]:
with pd.option_context("display.max_rows", None):
    display(indicator_meta)

with pd.option_context("display.max_rows", None):
    display(indicator_meta_gdp)

,INDICATOR_CODE,INDICATOR_NAME,SOURCE_NOTE,SOURCE_ORGANIZATION
0,SM.POP.TOTL.ZS,International migrant stock (% of population),International migrant stock is the number of p...,"United Nations Population Division, Trends in ..."
1,SM.POP.TOTL,"International migrant stock, total",International migrant stock is the number of p...,"United Nations Population Division, Trends in ..."
2,SM.POP.NETM,Net migration,Net migration is the net total of migrants dur...,United Nations Population Division. World Popu...
3,SI.RMT.COST.OB.ZS,Average transaction cost of sending remittance...,Average transaction cost of sending remittance...,"World Bank, Remittance Prices Worldwide, avail..."
4,SI.RMT.COST.IB.ZS,Average transaction cost of sending remittance...,Average transaction cost of sending remittance...,"World Bank, Remittance Prices Worldwide, avail..."
5,PX.REX.REER,Real effective exchange rate index (2010 = 100),Real effective exchange rate is the nominal ef...,"International Monetary Fund, International Fin..."
6,PA.NUS.FCRF,"Official exchange rate (LCU per US$, period av...",Official exchange rate refers to the exchange ...,"International Monetary Fund, International Fin..."
7,PA.NUS.ATLS,DEC alternative conversion factor (LCU per US$),The DEC alternative conversion factor is the u...,"International Monetary Fund, International Fin..."
8,NY.GDP.DEFL.ZS.AD,GDP deflator: linked series (base year varies ...,The GDP implicit deflator is calculated as the...,World Bank staff estimates based on World Bank...
9,NY.GDP.DEFL.KD.ZG.AD,"Inflation, GDP deflator: linked series (annual %)",Inflation as measured by the annual growth rat...,World Bank staff estimates based on World Bank...
10,IC.LGL.CRED.XQ,Strength of legal rights index (0=weak to 12=s...,Strength of legal rights index measures the de...,"World Bank, Doing Business project (http://www..."
11,IC.CRD.PUBL.ZS,Public credit registry coverage (% of adults),Public credit registry coverage reports the nu...,"World Bank, Doing Business project (http://www..."
12,IC.CRD.PRVT.ZS,Private credit bureau coverage (% of adults),Private credit bureau coverage reports the num...,"World Bank, Doing Business project (http://www..."
13,IC.CRD.INFO.XQ,Depth of credit information index (0=low to 8=...,Depth of credit information index measures rul...,"World Bank, Doing Business project (http://www..."
14,FX.OWN.TOTL.ZS,Account ownership at a financial institution o...,Account denotes the percentage of respondents ...,"Global Findex Database, World Bank (https://ww..."
15,FX.OWN.TOTL.YG.ZS,Account ownership at a financial institution o...,Account denotes the percentage of respondents ...,"Global Findex Database, World Bank (https://ww..."
16,FX.OWN.TOTL.SO.ZS,Account ownership at a financial institution o...,Account denotes the percentage of respondents ...,"Global Findex Database, World Bank (https://ww..."
17,FX.OWN.TOTL.PL.ZS,Account ownership at a financial institution o...,Account denotes the percentage of respondents ...,"Global Findex Database, World Bank (https://ww..."
18,FX.OWN.TOTL.OL.ZS,Account ownership at a financial institution o...,Account denotes the percentage of respondents ...,"Global Findex Database, World Bank (https://ww..."
19,FX.OWN.TOTL.MA.ZS,Account ownership at a financial institution o...,Account denotes the percentage of respondents ...,"Global Findex Database, World Bank (https://ww..."
20,FX.OWN.TOTL.FE.ZS,Account ownership at a financial institution o...,Account denotes the percentage of respondents ...,"Global Findex Database, World Bank (https://ww..."
21,FX.OWN.TOTL.60.ZS,Account ownership at a financial institution o...,Account denotes the percentage of respondents ...,"Global Findex Database, World Bank (https://ww..."
22,FX.OWN.TOTL.40.ZS,Account ownership at a financial institution o...,Account denotes the percentage of respondents ...,"Global Findex Database, World Bank (https://ww..."
23,FS.AST.PRVT.GD.ZS,Domestic credit to private sector (% of GDP),Domestic credit to private sector refers to fi...,"International Monetary Fund, International Fin..."
24,FS.AST.DOMS.GD.ZS,Domestic credit provided by financial sector (...,Domestic credit provided by the financial sect...,"International Monetary Fund, International Fin..."
25,FS.AST.DOMO.GD.ZS,Claims on other sectors of the domestic econom...,Claims on other sectors of the domestic econom...,"International Monetary Fund, International Fin..."
26,FS.AST.CGOV.GD.ZS,"Claims on central government, etc. (% GDP)",Claims on central government (IFS line 52AN or...,"International Monetary Fund, International Fin..."
27,FR.INR.RISK,Risk premium on lending (lending rate minus tr...,Risk premium on lending is the interest rate c...,"International Monetary Fund, International Fin..."
28,FR.INR.RINR,Real interest rate (%),Real interest rate is the lending interest rat...,"International Monetary Fund, International Fin..."
29,FR.INR.LNDP,Interest rate spread (lending rate minus depos...,Interest rate spread is the interest rate char...,"International Monetary Fund, International Fin..."
30,FR.INR.LEND,Lending interest rate (%),Lending rate is the bank rate that usually mee...,"International Monetary Fund, International Fin..."
31,FR.INR.DPST,Deposit interest rate (%),Deposit interest rate is the rate paid by comm...,"International Monetary Fund, International Fin..."
32,FP.WPI.TOTL,Wholesale price index (2010 = 100),Wholesale price index refers to a mix of agric...,"International Monetary Fund, International Fin..."
33,FP.CPI.TOTL.ZG,"Inflation, consumer prices (annual %)",Inflation as measured by the consumer price in...,"International Monetary Fund, International Fin..."
34,FP.CPI.TOTL,Consumer price index (2010 = 100),Consumer price index reflects changes in the c...,"International Monetary Fund, International Fin..."
35,FM.LBL.BMNY.ZG,Broad money growth (annual %),Broad money (IFS line 35L..ZK) is the sum of c...,"International Monetary Fund, International Fin..."
36,FM.LBL.BMNY.IR.ZS,Broad money to total reserves ratio,Broad money (IFS line 35L..ZK) is the sum of c...,"International Monetary Fund, International Fin..."
37,FM.LBL.BMNY.GD.ZS,Broad money (% of GDP),Broad money (IFS line 35L..ZK) is the sum of c...,"International Monetary Fund, International Fin..."
38,FM.LBL.BMNY.CN,Broad money (current LCU),Broad money (IFS line 35L..ZK) is the sum of c...,"International Monetary Fund, International Fin..."
39,FM.AST.PRVT.ZG.M3,Claims on private sector (annual growth as % o...,Claims on private sector (IFS line 32D..ZK or ...,"International Monetary Fund, International Fin..."
40,FM.AST.PRVT.GD.ZS,Monetary Sector credit to private sector (% GDP),Domestic credit to private sector refers to fi...,"International Monetary Fund, International Fin..."
41,FM.AST.NFRG.CN,Net foreign assets (current LCU),Net foreign assets are the sum of foreign asse...,"International Monetary Fund, International Fin..."
42,FM.AST.DOMS.CN,Net domestic credit (current LCU),Net domestic credit is the sum of net claims o...,"International Monetary Fund, International Fin..."
43,FM.AST.DOMO.ZG.M3,Claims on other sectors of the domestic econom...,Claims on other sectors of the domestic econom...,"International Monetary Fund, International Fin..."
44,FM.AST.CGOV.ZG.M3,Claims on central government (annual growth as...,Claims on central government (IFS line 32AN..Z...,"International Monetary Fund, International Fin..."
45,FI.RES.XGLD.CD,Total reserves minus gold (current US$),Total reserves minus gold comprise special dra...,"International Monetary Fund, International Fin..."
46,FI.RES.TOTL.MO,Total reserves in months of imports,Total reserves comprise holdings of monetary g...,"International Monetary Fund, International Fin..."
47,FI.RES.TOTL.DT.ZS,Total reserves (% of total external debt),International reserves to total external debt ...,"World Bank, International Debt Statistics."
48,FI.RES.TOTL.CD,"Total reserves (includes gold, current US$)",Total reserves comprise holdings of monetary g...,"International Monetary Fund, International Fin..."
49,FD.RES.LIQU.AS.ZS,Bank liquid reserves to bank assets ratio (%),Ratio of bank liquid reserves to bank assets i...,"International Monetary Fund, International Fin..."
50,FD.AST.PRVT.GD.ZS,Domestic credit to private sector by banks (% ...,Domestic credit to private sector by banks ref...,"International Monetary Fund, International Fin..."
51,FB.CBK.DPTR.P3,"Depositors with commercial banks (per 1,000 ad...",Depositors with commercial banks are the repor...,"International Monetary Fund, Financial Access ..."
52,FB.CBK.BRWR.P3,"Borrowers from commercial banks (per 1,000 adu...",Borrowers from commercial banks are the report...,"International Monetary Fund, Financial Access ..."
53,FB.CBK.BRCH.P5,"Commercial bank branches (per 100,000 adults)",Commercial bank branches are retail locations ...,"International Monetary Fund, Financial Access ..."
54,FB.BNK.CAPA.ZS,Bank capital to assets ratio (%),Bank capital to assets is the ratio of bank ca...,"International Monetary Fund, Financial Soundne..."
55,FB.ATM.TOTL.P5,"Automated teller machines (ATMs) (per 100,000 ...",Automated teller machines are computerized tel...,"International Monetary Fund, Financial Access ..."
56,FB.AST.NPER.ZS,Bank nonperforming loans to total gross loans (%),Bank nonperforming loans to total gross loans ...,"International Monetary Fund, Financial Soundne..."
57,DT.NFL.BOND.CD,"Portfolio investment, bonds (PPG + PNG) (NFL, ...",Bonds are securities issued with a fixed rate ...,"World Bank, International Debt Statistics."
58,CM.MKT.TRNR,"Stocks traded, turnover ratio of domestic shar...",Turnover ratio is the value of domestic shares...,World Federation of Exchanges database.
59,CM.MKT.TRAD.GD.ZS,"Stocks traded, total value (% of GDP)",The value of shares traded is the total number...,World Federation of Exchanges database.
60,CM.MKT.TRAD.CD,"Stocks traded, total value (current US$)",The value of shares traded is the total number...,World Federation of Exchanges database.
61,CM.MKT.LDOM.NO,"Listed domestic companies, total","Listed domestic companies, including foreign c...",World Federation of Exchanges database.
62,CM.MKT.LCAP.GD.ZS,Market capitalization of listed domestic compa...,Market capitalization (also known as market va...,World Federation of Exchanges database.
63,CM.MKT.LCAP.CD,Market capitalization of listed domestic compa...,Market capitalization (also known as market va...,World Federation of Exchanges database.
64,CM.MKT.INDX.ZG,S&P Global Equity Indices (annual % change),S&P Global Equity Indices measure the U.S. dol...,"Standard & Poor's, Global Stock Markets Factbo..."
65,BX.TRF.PWKR.DT.GD.ZS,"Personal remittances, received (% of GDP)",Personal remittances comprise personal transfe...,World Bank staff estimates based on IMF balanc...
66,BX.TRF.PWKR.CD.DT,"Personal remittances, received (current US$)",Personal remittances comprise personal transfe...,World Bank staff estimates based on IMF balanc...
67,BX.TRF.PWKR.CD,"Personal transfers, receipts (BoP, current US$)",Personal transfers consist of all current tran...,"International Monetary Fund, Balance of Paymen..."
68,BX.PEF.TOTL.CD.WD,"Portfolio equity, net inflows (BoP, current US$)",Portfolio equity includes net inflows from equ...,"International Monetary Fund, Balance of Paymen..."
69,BX.KLT.DINV.WD.GD.ZS,"Foreign direct investment, net inflows (% of GDP)",Foreign direct investment are the net inflows ...,"International Monetary Fund, International Fin..."
70,BX.KLT.DINV.CD.WD,"Foreign direct investment, net inflows (BoP, c...",Foreign direct investment refers to direct inv...,"International Monetary Fund, Balance of Paymen..."
71,BN.KLT.PTXL.CD,"Portfolio Investment, net (BoP, current US$)",Portfolio investment covers transactions in eq...,"International Monetary Fund, Balance of Paymen..."
72,BN.KLT.DINV.CD,"Foreign direct investment, net (BoP, current US$)",Foreign direct investment are the net inflows ...,"International Monetary Fund, Balance of Paymen..."
73,BM.TRF.PWKR.CD.DT,"Personal remittances, paid (current US$)",Personal remittances comprise personal transfe...,World Bank staff estimates based on IMF balanc...
74,BM.KLT.DINV.WD.GD.ZS,"Foreign direct investment, net outflows (% of ...",Foreign direct investment refers to direct inv...,"International Monetary Fund, Balance of Paymen..."
75,BM.KLT.DINV.CD.WD,"Foreign direct investment, net outflows (BoP, ...",Foreign direct investment refers to direct inv...,"International Monetary Fund, Balance of Paymen..."

,INDICATOR_CODE,INDICATOR_NAME,SOURCE_NOTE,SOURCE_ORGANIZATION
0,NY.GDP.MKTP.KD.ZG,GDP growth (annual %),Gross domestic product is the total income ear...,"Country official statistics, National Statisti..."

In [ ]:
selected_codes = [
    "NY.GDP.MKTP.KD.ZG",
    "FS.AST.PRVT.GD.ZS",
    "FB.CBK.BRCH.P5",
    "FB.ATM.TOTL.P5",
    "CM.MKT.LCAP.GD.ZS",
    "FR.INR.LNDP",
    "FM.LBL.BMNY.GD.ZS",
    "BX.KLT.DINV.WD.GD.ZS",
    "FB.AST.NPER.ZS",
    "NY.GDP.DEFL.KD.ZG.AD"
]

df_filtered = df[df["Indicator Code"].isin(selected_codes)]
display(df_filtered)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
9,Aruba,ABW,"Inflation, GDP deflator: linked series (annual %)",NY.GDP.DEFL.KD.ZG.AD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.958897,6.831287,-1.002799,-3.178167,3.477547,6.094208,-0.871325,-4.990168,3.412842,NaN
23,Aruba,ABW,Domestic credit to private sector (% of GDP),FS.AST.PRVT.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.240539,56.626871,57.221975,57.246514,55.965159,58.785552,79.287234,63.728884,56.763274,NaN
29,Aruba,ABW,Interest rate spread (lending rate minus depos...,FR.INR.LNDP,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,5.100000,4.900000,4.700000,4.800000,3.500000,5.500000,4.700000,4.300000,NaN
37,Aruba,ABW,Broad money (% of GDP),FM.LBL.BMNY.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,69.586944,71.741782,78.012143,76.595426,74.635468,75.173399,104.736611,96.593883,87.372363,NaN
53,Aruba,ABW,"Commercial bank branches (per 100,000 adults)",FB.CBK.BRCH.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,19.060000,18.860000,19.830000,18.510000,17.240000,14.840000,11.340000,12.410000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20193,Zimbabwe,ZWE,"Commercial bank branches (per 100,000 adults)",FB.CBK.BRCH.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,14.770000,6.010000,5.820000,5.640000,5.480000,3.750000,4.170000,6.210000,NaN,NaN
20195,Zimbabwe,ZWE,"Automated teller machines (ATMs) (per 100,000 ...",FB.ATM.TOTL.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,6.030000,7.160000,7.070000,6.890000,6.630000,6.400000,6.160000,6.050000,NaN,NaN
20196,Zimbabwe,ZWE,Bank nonperforming loans to total gross loans (%),FB.AST.NPER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20202,Zimbabwe,ZWE,Market capitalization of listed domestic compa...,CM.MKT.LCAP.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20209,Zimbabwe,ZWE,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.425173,1.999687,1.669274,1.746885,2.101721,1.142806,0.699034,0.881174,1.247870,NaN

In [ ]:
df_gdp_filtered = df_gdp[df_gdp["Indicator Code"].isin(selected_codes)]

display(df_gdp_filtered)

,Country Name,Country Code,Indicator Name,Indicator Code,1961,1962,1963,1964,1965,1966,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.611480,1.234335,3.493430,3.212471,1.225112,-23.897990,14.730616,10.636431,7.706798,6.810777
1,Africa Eastern and Southern,AFE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,0.418937,7.937038,5.623764,4.649241,5.138168,4.827421,...,2.934030,2.130117,2.677524,2.705194,2.030077,-2.817572,4.578772,3.722717,1.931160,2.763839
2,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.451315,2.260314,2.647003,1.189228,3.911603,-2.351101,-20.738839,-6.240172,2.266944,NaN
3,Africa Western and Central,AFW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1.869593,3.726090,7.038388,5.364089,4.105339,-1.513011,...,2.932864,0.194316,2.296349,2.904664,3.281683,-3.730630,2.549691,4.472795,3.662428,4.585674
4,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.763178,-1.700530,-0.149396,-0.594411,-0.204680,-4.042447,2.102753,4.216003,1.263308,4.423907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.916231,5.571775,4.825656,3.406632,4.756801,-5.340275,10.745656,4.278499,4.067627,4.573097
262,"Yemen, Rep.",YEM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-27.994546,-9.375124,-5.071796,0.752448,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,3.844734,6.177931,7.373709,7.939609,6.122798,4.438386,...,1.321862,0.664552,1.157947,1.556784,0.259936,-6.168918,4.858649,2.058137,0.806105,0.534844
264,Zambia,ZMB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,...,2.920375,3.755100,3.525863,4.034494,1.441306,-2.785055,6.234922,5.211224,5.367943,3.820048
265,Zimbabwe,ZWE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,...,1.779854,0.755794,4.734411,5.009922,-6.332450,-7.816951,8.468017,6.139263,5.350869,1.742395

In [ ]:
display(country_meta)

,Country Code,Region,IncomeGroup,SpecialNotes,TableName
0,ABW,Latin America & Caribbean,High income,NaN,Aruba
1,AFE,NaN,NaN,"26 countries, stretching from the Red Sea in t...",Africa Eastern and Southern
2,AFG,South Asia,Low income,The reporting period for national accounts dat...,Afghanistan
3,AFW,NaN,NaN,"22 countries, stretching from the westernmost ...",Africa Western and Central
4,AGO,Sub-Saharan Africa,Lower middle income,The World Bank systematically assesses the app...,Angola
...,...,...,...,...,...
260,XKX,Europe & Central Asia,Upper middle income,NaN,Kosovo
261,YEM,Middle East & North Africa,Low income,The World Bank systematically assesses the app...,"Yemen, Rep."
262,ZAF,Sub-Saharan Africa,Upper middle income,Fiscal year end: March 31; reporting period fo...,South Africa
263,ZMB,Sub-Saharan Africa,Lower middle income,National accounts data were rebased to reflect...,Zambia
264,ZWE,Sub-Saharan Africa,Lower middle income,National Accounts data are reported in Zimbabw...,Zimbabwe

In [ ]:
regions = country_meta[
    country_meta["Region"].isna() & country_meta["IncomeGroup"].isna()
]

region_codes = regions["Country Code"].tolist()

#display(regions)

is_region = df_filtered["Country Code"].isin(region_codes)
df_filtered_no_regions = df_filtered[is_region == False]
#df_filtered_just_regions = df_filtered[is_region == True]

display(df_filtered_no_regions)
#display(df_filtered_just_regions)
#display(df_filtered)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
9,Aruba,ABW,"Inflation, GDP deflator: linked series (annual %)",NY.GDP.DEFL.KD.ZG.AD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.958897,6.831287,-1.002799,-3.178167,3.477547,6.094208,-0.871325,-4.990168,3.412842,NaN
23,Aruba,ABW,Domestic credit to private sector (% of GDP),FS.AST.PRVT.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.240539,56.626871,57.221975,57.246514,55.965159,58.785552,79.287234,63.728884,56.763274,NaN
29,Aruba,ABW,Interest rate spread (lending rate minus depos...,FR.INR.LNDP,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,5.100000,4.900000,4.700000,4.800000,3.500000,5.500000,4.700000,4.300000,NaN
37,Aruba,ABW,Broad money (% of GDP),FM.LBL.BMNY.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,69.586944,71.741782,78.012143,76.595426,74.635468,75.173399,104.736611,96.593883,87.372363,NaN
53,Aruba,ABW,"Commercial bank branches (per 100,000 adults)",FB.CBK.BRCH.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,19.060000,18.860000,19.830000,18.510000,17.240000,14.840000,11.340000,12.410000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20193,Zimbabwe,ZWE,"Commercial bank branches (per 100,000 adults)",FB.CBK.BRCH.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,14.770000,6.010000,5.820000,5.640000,5.480000,3.750000,4.170000,6.210000,NaN,NaN
20195,Zimbabwe,ZWE,"Automated teller machines (ATMs) (per 100,000 ...",FB.ATM.TOTL.P5,NaN,NaN,NaN,NaN,NaN,NaN,...,6.030000,7.160000,7.070000,6.890000,6.630000,6.400000,6.160000,6.050000,NaN,NaN
20196,Zimbabwe,ZWE,Bank nonperforming loans to total gross loans (%),FB.AST.NPER.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20202,Zimbabwe,ZWE,Market capitalization of listed domestic compa...,CM.MKT.LCAP.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20209,Zimbabwe,ZWE,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,2.425173,1.999687,1.669274,1.746885,2.101721,1.142806,0.699034,0.881174,1.247870,NaN

In [ ]:
regions_gdp = country_meta_gdp[
    country_meta_gdp["Region"].isna() & country_meta_gdp["IncomeGroup"].isna()
]

region_codes_gdp = regions_gdp["Country Code"].tolist()

is_region_gdp = df_gdp_filtered["Country Code"].isin(region_codes_gdp)
df_gdp_filtered_no_regions = df_gdp_filtered[is_region_gdp == False]

display(df_gdp_filtered_no_regions)

,Country Name,Country Code,Indicator Name,Indicator Code,1961,1962,1963,1964,1965,1966,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.611480,1.234335,3.493430,3.212471,1.225112,-23.897990,14.730616,10.636431,7.706798,6.810777
2,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.451315,2.260314,2.647003,1.189228,3.911603,-2.351101,-20.738839,-6.240172,2.266944,NaN
4,Angola,AGO,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,0.763178,-1.700530,-0.149396,-0.594411,-0.204680,-4.042447,2.102753,4.216003,1.263308,4.423907
5,Albania,ALB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,2.227704,3.908936,3.283176,3.671419,2.062578,-3.313756,8.969576,4.826801,4.015417,4.045928
6,Andorra,AND,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,1.434140,3.709678,0.346072,1.588765,2.015548,-11.183940,8.286779,9.564612,2.583555,3.371820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.916231,5.571775,4.825656,3.406632,4.756801,-5.340275,10.745656,4.278499,4.067627,4.573097
262,"Yemen, Rep.",YEM,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-27.994546,-9.375124,-5.071796,0.752448,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,3.844734,6.177931,7.373709,7.939609,6.122798,4.438386,...,1.321862,0.664552,1.157947,1.556784,0.259936,-6.168918,4.858649,2.058137,0.806105,0.534844
264,Zambia,ZMB,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,...,2.920375,3.755100,3.525863,4.034494,1.441306,-2.785055,6.234922,5.211224,5.367943,3.820048
265,Zimbabwe,ZWE,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,...,1.779854,0.755794,4.734411,5.009922,-6.332450,-7.816951,8.468017,6.139263,5.350869,1.742395

In [ ]:
year_cols = [str(year) for year in range(1960, 2024)]
werte_pro_jahr = df_filtered_no_regions[year_cols].notna().sum()

display(werte_pro_jahr)

1960      99
1961     102
1962     116
1963     121
1964     127
        ...
2019    1379
2020    1351
2021    1307
2022     879
2023       0
Length: 64, dtype: int64

In [ ]:
year_cols_gdp = [str(year) for year in range(1961, 2024)]
werte_pro_jahr_gdp = df_gdp_filtered_no_regions[year_cols_gdp].notna().sum()
display(werte_pro_jahr_gdp)

1961    107
1962    112
1963    112
1964    112
1965    112
       ...
2019    210
2020    210
2021    210
2022    209
2023    203
Length: 63, dtype: int64

In [ ]:
years_to_keep = [str(year) for year in range(2004, 2022)]
id_cols = ["Country Name", "Indicator Name"]
df_filtered_no_regions_relevant_years = df_filtered_no_regions[id_cols + years_to_keep]
display(df_filtered_no_regions_relevant_years)

,Country Name,Indicator Name,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
9,Aruba,"Inflation, GDP deflator: linked series (annual %)",2.809909,5.067499,3.484346,5.166893,4.262448,1.703281,-1.223408,4.005673,0.184033,-1.995948,3.958897,6.831287,-1.002799,-3.178167,3.477547,6.094208,-0.871325,-4.990168
23,Aruba,Domestic credit to private sector (% of GDP),51.785230,54.060701,53.884120,51.727256,50.658458,55.893041,58.800657,56.250434,58.685903,59.163673,60.240539,56.626871,57.221975,57.246514,55.965159,58.785552,79.287234,63.728884
29,Aruba,Interest rate spread (lending rate minus depos...,6.500000,6.900000,5.100000,5.900000,6.300000,7.300000,8.400000,7.400000,7.000000,5.300000,5.000000,5.100000,4.900000,4.700000,4.800000,3.500000,5.500000,4.700000
37,Aruba,Broad money (% of GDP),56.620832,57.446790,56.196562,53.544999,58.783489,69.203660,71.827045,66.894434,73.040742,67.419628,69.586944,71.741782,78.012143,76.595426,74.635468,75.173399,104.736611,96.593883
53,Aruba,"Commercial bank branches (per 100,000 adults)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.960000,21.960000,19.290000,19.060000,18.860000,19.830000,18.510000,17.240000,14.840000,11.340000,12.410000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20193,Zimbabwe,"Commercial bank branches (per 100,000 adults)",2.880000,3.910000,3.670000,4.090000,3.410000,4.540000,4.800000,6.220000,12.980000,13.710000,14.770000,6.010000,5.820000,5.640000,5.480000,3.750000,4.170000,6.210000
20195,Zimbabwe,"Automated teller machines (ATMs) (per 100,000 ...",NaN,NaN,7.220000,7.700000,7.470000,7.940000,5.400000,4.410000,4.920000,4.850000,6.030000,7.160000,7.070000,6.890000,6.630000,6.400000,6.160000,6.050000
20196,Zimbabwe,Bank nonperforming loans to total gross loans (%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20202,Zimbabwe,Market capitalization of listed domestic compa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20209,Zimbabwe,"Foreign direct investment, net inflows (% of GDP)",0.149855,1.786206,0.734768,1.301978,1.168557,1.086305,1.018022,2.441511,2.044131,1.954060,2.425173,1.999687,1.669274,1.746885,2.101721,1.142806,0.699034,0.881174

In [ ]:
df_gdp_filtered_no_regions_relevant_years = df_gdp_filtered_no_regions[id_cols + years_to_keep]

display(df_gdp_filtered_no_regions_relevant_years)

,Country Name,Indicator Name,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,GDP growth (annual %),7.293728,-0.383138,1.127411,3.089544,1.835755,-11.677741,-2.733457,3.369237,-1.040800,6.431461,1.426099,3.611480,1.234335,3.493430,3.212471,1.225112,-23.897990,14.730616
2,Afghanistan,GDP growth (annual %),1.414118,11.229715,5.357403,13.826320,3.924984,21.390528,14.362441,0.426355,12.752287,5.600745,2.724543,1.451315,2.260314,2.647003,1.189228,3.911603,-2.351101,-20.738839
4,Angola,GDP growth (annual %),11.419863,14.154778,11.841818,13.002689,10.786636,1.995589,5.293666,3.593870,8.503123,4.883061,4.655724,0.763178,-1.700530,-0.149396,-0.594411,-0.204680,-4.042447,2.102753
5,Albania,GDP growth (annual %),5.266262,5.130822,6.018981,6.500093,6.907062,2.690752,2.973154,2.463517,0.984130,1.707228,2.240227,2.227704,3.908936,3.283176,3.671419,2.062578,-3.313756,8.969576
6,Andorra,GDP growth (annual %),8.135676,5.397796,4.808689,1.553188,-5.559186,-5.302847,-1.974958,-0.008070,-4.974444,-3.547597,2.504466,1.434140,3.709678,0.346072,1.588765,2.015548,-11.183940,8.286779
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,GDP growth (annual %),NaN,NaN,NaN,NaN,NaN,5.034854,4.939951,6.319810,1.712196,5.340799,3.348805,5.916231,5.571775,4.825656,3.406632,4.756801,-5.340275,10.745656
262,"Yemen, Rep.",GDP growth (annual %),3.972696,5.591748,3.170409,3.338428,3.647569,3.866230,7.701286,-12.714897,2.392990,4.823519,-0.188690,-27.994546,-9.375124,-5.071796,0.752448,NaN,NaN,NaN
263,South Africa,GDP growth (annual %),4.554560,5.277052,5.603806,5.360474,3.191044,-1.538089,3.039733,3.168556,2.396232,2.485468,1.413826,1.321862,0.664552,1.157947,1.556784,0.259936,-6.168918,4.858649
264,Zambia,GDP growth (annual %),7.032395,7.235599,7.903694,8.352436,7.773896,9.220348,10.298223,5.569252,7.597381,5.057537,4.693283,2.920375,3.755100,3.525863,4.034494,1.441306,-2.785055,6.234922
265,Zimbabwe,GDP growth (annual %),-5.807540,-5.711125,-3.461403,-3.653251,-17.668999,13.272055,19.675408,14.193916,16.665429,1.989486,2.376986,1.779854,0.755794,4.734411,5.009922,-6.332450,-7.816951,8.468017

In [ ]:
df_filtered_no_regions_relevant_years = pd.concat(
    [
        df_filtered_no_regions_relevant_years,
        df_gdp_filtered_no_regions_relevant_years
    ],
    ignore_index=True
)

display(df_filtered_no_regions_relevant_years)

,Country Name,Indicator Name,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,"Inflation, GDP deflator: linked series (annual %)",2.809909,5.067499,3.484346,5.166893,4.262448,1.703281,-1.223408,4.005673,0.184033,-1.995948,3.958897,6.831287,-1.002799,-3.178167,3.477547,6.094208,-0.871325,-4.990168
1,Aruba,Domestic credit to private sector (% of GDP),51.785230,54.060701,53.884120,51.727256,50.658458,55.893041,58.800657,56.250434,58.685903,59.163673,60.240539,56.626871,57.221975,57.246514,55.965159,58.785552,79.287234,63.728884
2,Aruba,Interest rate spread (lending rate minus depos...,6.500000,6.900000,5.100000,5.900000,6.300000,7.300000,8.400000,7.400000,7.000000,5.300000,5.000000,5.100000,4.900000,4.700000,4.800000,3.500000,5.500000,4.700000
3,Aruba,Broad money (% of GDP),56.620832,57.446790,56.196562,53.544999,58.783489,69.203660,71.827045,66.894434,73.040742,67.419628,69.586944,71.741782,78.012143,76.595426,74.635468,75.173399,104.736611,96.593883
4,Aruba,"Commercial bank branches (per 100,000 adults)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.960000,21.960000,19.290000,19.060000,18.860000,19.830000,18.510000,17.240000,14.840000,11.340000,12.410000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2175,Kosovo,GDP growth (annual %),NaN,NaN,NaN,NaN,NaN,5.034854,4.939951,6.319810,1.712196,5.340799,3.348805,5.916231,5.571775,4.825656,3.406632,4.756801,-5.340275,10.745656
2176,"Yemen, Rep.",GDP growth (annual %),3.972696,5.591748,3.170409,3.338428,3.647569,3.866230,7.701286,-12.714897,2.392990,4.823519,-0.188690,-27.994546,-9.375124,-5.071796,0.752448,NaN,NaN,NaN
2177,South Africa,GDP growth (annual %),4.554560,5.277052,5.603806,5.360474,3.191044,-1.538089,3.039733,3.168556,2.396232,2.485468,1.413826,1.321862,0.664552,1.157947,1.556784,0.259936,-6.168918,4.858649
2178,Zambia,GDP growth (annual %),7.032395,7.235599,7.903694,8.352436,7.773896,9.220348,10.298223,5.569252,7.597381,5.057537,4.693283,2.920375,3.755100,3.525863,4.034494,1.441306,-2.785055,6.234922
2179,Zimbabwe,GDP growth (annual %),-5.807540,-5.711125,-3.461403,-3.653251,-17.668999,13.272055,19.675408,14.193916,16.665429,1.989486,2.376986,1.779854,0.755794,4.734411,5.009922,-6.332450,-7.816951,8.468017

In [ ]:
print(df_filtered_no_regions_relevant_years.shape)
print(df_filtered_no_regions_relevant_years.columns)

(2180, 20)
Index(['Country Name', 'Indicator Name', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021'],
      dtype='str')

In [ ]:
df_long = df_filtered_no_regions_relevant_years.melt(
    id_vars = id_cols,
    value_vars = years_to_keep,
    var_name = "Year",
    value_name = "Value"
)

df_long["Year"] = df_long["Year"].astype(int)
df_long["Value"] = pd.to_numeric(df_long["Value"], errors="coerce")

display(df_long)
print(df_long.shape)

,Country Name,Indicator Name,Year,Value
0,Aruba,"Inflation, GDP deflator: linked series (annual %)",2004,2.809909
1,Aruba,Domestic credit to private sector (% of GDP),2004,51.785230
2,Aruba,Interest rate spread (lending rate minus depos...,2004,6.500000
3,Aruba,Broad money (% of GDP),2004,56.620832
4,Aruba,"Commercial bank branches (per 100,000 adults)",2004,NaN
...,...,...,...,...
39235,Kosovo,GDP growth (annual %),2021,10.745656
39236,"Yemen, Rep.",GDP growth (annual %),2021,NaN
39237,South Africa,GDP growth (annual %),2021,4.858649
39238,Zambia,GDP growth (annual %),2021,6.234922
39239,Zimbabwe,GDP growth (annual %),2021,8.468017

(39240, 4)

In [ ]:
df_panel = df_long.pivot_table(
    index = ["Country Name", "Year"],
    columns = ["Indicator Name"],
    values = "Value"
).reset_index()

display(df_panel)
print(df_panel.shape)
print(df_panel.columns)

Indicator Name,Country Name,Year,"Automated teller machines (ATMs) (per 100,000 adults)",Bank nonperforming loans to total gross loans (%),Broad money (% of GDP),"Commercial bank branches (per 100,000 adults)",Domestic credit to private sector (% of GDP),"Foreign direct investment, net inflows (% of GDP)",GDP growth (annual %),"Inflation, GDP deflator: linked series (annual %)","Interest rate spread (lending rate minus deposit rate, %)",Market capitalization of listed domestic companies (% of GDP)
0,Afghanistan,2004,0.02,NaN,NaN,0.37,NaN,3.577104,1.414118,11.271432,NaN,NaN
1,Afghanistan,2005,0.06,NaN,NaN,0.58,NaN,4.368673,11.229715,10.912774,NaN,NaN
2,Afghanistan,2006,0.12,NaN,23.343865,0.92,4.842857,3.413773,5.357403,7.199751,NaN,NaN
3,Afghanistan,2007,0.21,NaN,23.833664,1.24,6.839982,1.935702,13.826320,22.527756,NaN,NaN
4,Afghanistan,2008,0.30,NaN,29.512281,1.48,9.388328,0.455360,3.924984,2.096289,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3826,Zimbabwe,2017,6.89,NaN,35.467144,5.64,16.875108,1.746885,4.734411,3.056905,3.640000,NaN
3827,Zimbabwe,2018,6.63,NaN,14.379262,5.48,5.830265,2.101721,5.009922,200.769578,4.599167,NaN
3828,Zimbabwe,2019,6.40,NaN,16.504433,3.75,5.237706,1.142806,-6.332450,225.394648,13.206667,NaN
3829,Zimbabwe,2020,6.16,NaN,14.871527,4.17,5.415074,0.699034,-7.816951,604.945864,28.490000,NaN
3830,Zimbabwe,2021,6.05,NaN,14.901908,6.21,6.988543,0.881174,8.468017,113.294981,37.417500,NaN

(3831, 12)
Index(['Country Name', 'Year',
       'Automated teller machines (ATMs) (per 100,000 adults)',
       'Bank nonperforming loans to total gross loans (%)',
       'Broad money (% of GDP)',
       'Commercial bank branches (per 100,000 adults)',
       'Domestic credit to private sector (% of GDP)',
       'Foreign direct investment, net inflows (% of GDP)',
       'GDP growth (annual %)',
       'Inflation, GDP deflator: linked series (annual %)',
       'Interest rate spread (lending rate minus deposit rate, %)',
       'Market capitalization of listed domestic companies (% of GDP)'],
      dtype='str', name='Indicator Name')

In [ ]:
df_panel = df_panel.rename(columns={
    "GDP growth (annual %)": "gdp_growth",
    "Domestic credit to private sector (% of GDP)": "domestic_credit",
    "Commercial bank branches (per 100,000 adults)": "bank_branches",
    "Automated teller machines (ATMs) (per 100,000 adults)": "atms",
    "Market capitalization of listed domestic companies (% of GDP)": "market_cap",
    "Interest rate spread (lending rate minus deposit rate, %)": "interest_spread",
    "Broad money (% of GDP)": "broad_money",
    "Foreign direct investment, net inflows (% of GDP)": "fdi_inflows",
    "Bank nonperforming loans to total gross loans (%)": "nonperforming_loans",
    "Inflation, GDP deflator: linked series (annual %)": "inflation"
})

display(df_panel)

Indicator Name,Country Name,Year,atms,nonperforming_loans,broad_money,bank_branches,domestic_credit,fdi_inflows,gdp_growth,inflation,interest_spread,market_cap
0,Afghanistan,2004,0.02,NaN,NaN,0.37,NaN,3.577104,1.414118,11.271432,NaN,NaN
1,Afghanistan,2005,0.06,NaN,NaN,0.58,NaN,4.368673,11.229715,10.912774,NaN,NaN
2,Afghanistan,2006,0.12,NaN,23.343865,0.92,4.842857,3.413773,5.357403,7.199751,NaN,NaN
3,Afghanistan,2007,0.21,NaN,23.833664,1.24,6.839982,1.935702,13.826320,22.527756,NaN,NaN
4,Afghanistan,2008,0.30,NaN,29.512281,1.48,9.388328,0.455360,3.924984,2.096289,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3826,Zimbabwe,2017,6.89,NaN,35.467144,5.64,16.875108,1.746885,4.734411,3.056905,3.640000,NaN
3827,Zimbabwe,2018,6.63,NaN,14.379262,5.48,5.830265,2.101721,5.009922,200.769578,4.599167,NaN
3828,Zimbabwe,2019,6.40,NaN,16.504433,3.75,5.237706,1.142806,-6.332450,225.394648,13.206667,NaN
3829,Zimbabwe,2020,6.16,NaN,14.871527,4.17,5.415074,0.699034,-7.816951,604.945864,28.490000,NaN
3830,Zimbabwe,2021,6.05,NaN,14.901908,6.21,6.988543,0.881174,8.468017,113.294981,37.417500,NaN

In [ ]:
print(df_panel.shape)
display(df_panel.head())
#display(df_panel.isna().sum())

(3831, 12)

Indicator Name,Country Name,Year,atms,nonperforming_loans,broad_money,bank_branches,domestic_credit,fdi_inflows,gdp_growth,inflation,interest_spread,market_cap
0,Afghanistan,2004,0.02,NaN,NaN,0.37,NaN,3.577104,1.414118,11.271432,NaN,NaN
1,Afghanistan,2005,0.06,NaN,NaN,0.58,NaN,4.368673,11.229715,10.912774,NaN,NaN
2,Afghanistan,2006,0.12,NaN,23.343865,0.92,4.842857,3.413773,5.357403,7.199751,NaN,NaN
3,Afghanistan,2007,0.21,NaN,23.833664,1.24,6.839982,1.935702,13.826320,22.527756,NaN,NaN
4,Afghanistan,2008,0.30,NaN,29.512281,1.48,9.388328,0.455360,3.924984,2.096289,NaN,NaN

Indicator Name
Country Name              0
Year                      0
atms                    850
nonperforming_loans    1983
broad_money            1029
bank_branches           689
domestic_credit         841
fdi_inflows             367
gdp_growth               79
inflation               117
interest_spread        1650
market_cap             2502
dtype: int64